version: "3"
services:
  discord-bot:
    build: 
      context: ..
      dockerfile: .devcontainer/discord-bot/Dockerfile
    volumes:
      - ..:/discord-bot
    init: true
    tty: true

  classroom:
    build: 
      context: ..
      dockerfile: .devcontainer/classroom/Dockerfile
    volumes:
      - ..:/classroom
    init: true
    tty: true

  reminder:
    build: 
      context: ..
      dockerfile: .devcontainer/reminder/Dockerfile
    volumes:
      - ..:/reminder
    init: true
    tty: true