version: "3"
services:
  discord-bot:
    build:
      context: ..
      dockerfile: .devcontainer/discord-bot/Dockerfile
    volumes:
      - ..:/dry
    init: true
    tty: true

  classroom:
    build:
      context: ..
      dockerfile: .devcontainer/classroom/Dockerfile
    volumes:
      - ..:/dry
    init: true
    tty: true

  reminder:
    build:
      context: ..
      dockerfile: .devcontainer/reminder/Dockerfile
    volumes:
      - ..:/dry
    env_file:
      - ../reminder/.env
    ports:
      - ${GRPC_PORT:-58946}:${GRPC_PORT:-58946}
    init: true
    tty: true

  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    volumes:
      - ../surrealdb:/surrealdb
    user: root
    command: start --auth --user root --pass root file:/surrealdb/databese.db
