version: "3"
services:
  discord-bot:
    build:
      context: ..
      dockerfile: .devcontainer/discord-bot/Dockerfile
    volumes:
      - ..:/dry
    init: true
    tty: true

  classroom:
    build:
      context: ..
      dockerfile: .devcontainer/classroom/Dockerfile
    volumes:
      - ..:/dry
    env_file:
      - ../classroom/.env
    ports:
      - "${OAUTH_PORT:-8888}:${OAUTH_PORT:-8888}"
    init: true
    tty: true
  reminder:
    build:
      context: ..
      dockerfile: .devcontainer/reminder/Dockerfile
    volumes:
      - ..:/dry
    # env_file:
    #   - ../reminder/.env
    ports:
      - ${GRPC_PORT:-58946}:${GRPC_PORT:-58946}
    init: true
    tty: true
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data
      - ../postgresql/init:/docker-entrypoint-initdb.d
    env_file:
      - ../classroom/.env
