# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discorbot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscorbot.proto\x12\x0c\x64ry.reminder\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\\\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12,\n\x08remindAt\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03who\x18\x04 \x01(\t\")\n\x05Tasks\x12 \n\x04task\x18\x01 \x03(\x0b\x32\x12.dry.reminder.Task\"]\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12,\n\x08remindAt\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03who\x18\x03 \x01(\t\"+\n\x0fListTaskRequest\x12\x10\n\x03who\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_who\"\x1f\n\x11\x44\x65leteTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xdd\x01\n\x0bTaskService\x12\x43\n\nCreateTask\x12\x1f.dry.reminder.CreateTaskRequest\x1a\x12.dry.reminder.Task\"\x00\x12@\n\x08ListTask\x12\x1d.dry.reminder.ListTaskRequest\x1a\x13.dry.reminder.Tasks\"\x00\x12G\n\nDeleteTask\x12\x1f.dry.reminder.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discorbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=95
  _globals['_TASK']._serialized_end=187
  _globals['_TASKS']._serialized_start=189
  _globals['_TASKS']._serialized_end=230
  _globals['_CREATETASKREQUEST']._serialized_start=232
  _globals['_CREATETASKREQUEST']._serialized_end=325
  _globals['_LISTTASKREQUEST']._serialized_start=327
  _globals['_LISTTASKREQUEST']._serialized_end=370
  _globals['_DELETETASKREQUEST']._serialized_start=372
  _globals['_DELETETASKREQUEST']._serialized_end=403
  _globals['_TASKSERVICE']._serialized_start=406
  _globals['_TASKSERVICE']._serialized_end=627
# @@protoc_insertion_point(module_scope)
