# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: classroom.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class AuthUrl(betterproto.Message):
    url: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class NewAuthRequest(betterproto.Message):
    who: str = betterproto.string_field(1)


class AuthServiceStub(betterproto.ServiceStub):
    async def new_auth(
        self,
        new_auth_request: "NewAuthRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AuthUrl":
        return await self._unary_unary(
            "/dry.classroom.AuthService/NewAuth",
            new_auth_request,
            AuthUrl,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class AuthServiceBase(ServiceBase):
    async def new_auth(self, new_auth_request: "NewAuthRequest") -> "AuthUrl":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_new_auth(
        self, stream: "grpclib.server.Stream[NewAuthRequest, AuthUrl]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.new_auth(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/dry.classroom.AuthService/NewAuth": grpclib.const.Handler(
                self.__rpc_new_auth,
                grpclib.const.Cardinality.UNARY_UNARY,
                NewAuthRequest,
                AuthUrl,
            ),
        }
